# Generated by Django 3.2.25 on 2025-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_administrator',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this back office', verbose_name='Administrator ?'),
        ),
        migrations.AddField(
            model_name='user',
            name='osm_token',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state_relay',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
