# Generated by Django 3.2.25 on 2025-07-19 12:09

from django.db import migrations


def set_is_administrator(apps, schema_editor):
    User = apps.get_model("account", "User")
    User.objects.update(is_administrator=True)


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_auto_20250719_1138"),
    ]

    operations = [
        migrations.RunPython(
            set_is_administrator, reverse_code=migrations.RunPython.noop
        )
    ]
