# Generated by Django 3.1.1 on 2020-09-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('icon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tags', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('group_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('thematiques', 'Thematiques'), ('base_maps', 'Base Maps')], max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('group_sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('layer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('protocol_carto', models.CharField(choices=[('wmts', 'Wmts'), ('wms', 'Wms'), ('wfs', 'Wfs')], max_length=5)),
                ('color', models.CharField(max_length=30)),
                ('cercle_icon', models.ImageField(upload_to='')),
                ('square_icon', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('opacity', models.BooleanField(default=True)),
                ('metadata', models.BooleanField(default=True)),
                ('share', models.BooleanField(default=True)),
                ('external_prov', models.ManyToManyField(blank=True, to='provider.External')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='group.icon')),
                ('vector_prov', models.ManyToManyField(blank=True, to='provider.Vector')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='group.icon'),
        ),
        migrations.AddField(
            model_name='group',
            name='type_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.type'),
        ),
    ]
