# Generated by Django 3.1.2 on 2020-10-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20201016_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='path',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
