# Generated by Django 3.1.2 on 2020-10-17 00:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_icon_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='category',
            field=models.TextField(default='Custom', unique=True),
        ),
        migrations.AlterField(
            model_name='icon',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=10),
        ),
    ]
