# Generated by Django 3.1.2 on 2020-10-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20201017_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='category',
            field=models.TextField(default='Custom'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='path',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
