# Generated by Django 3.1.2 on 2020-10-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20201017_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
