# Generated by Django 3.1.2 on 2020-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20201017_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='attribution',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='icon',
            name='path',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
