# Generated by Django 3.1.2 on 2020-10-17 10:49

from django.db import migrations, models
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20201017_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='path',
            field=models.ImageField(default=None, upload_to=group.models.get_upload_path),
        ),
    ]
