# Generated by Django 3.1.2 on 2020-10-17 10:57

from django.db import migrations, models
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20201017_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='attribution',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='icon',
            name='path',
            field=models.FileField(default=None, upload_to=group.models.get_upload_path),
        ),
    ]
