# Generated by Django 3.1.3 on 2020-11-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20201124_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maps',
            new_name='Map',
        ),
    ]
