# Generated by Django 3.1.3 on 2020-11-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_auto_20201124_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='display_name',
            new_name='name',
        ),
    ]
