# Generated by Django 3.1.3 on 2020-11-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_auto_20201125_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type_group',
            field=models.CharField(choices=[('thematiques', 'Thematiques'), ('base_maps', 'Base Maps')], max_length=50),
        ),
    ]
