# Generated by Django 3.1.4 on 2020-12-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20201125_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
