# Generated by Django 3.1.5 on 2021-01-15 12:45

from django.db import migrations, models
import django.db.models.deletion
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_auto_20210110_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='external_prov',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='vector_prov',
        ),
        migrations.AddField(
            model_name='layer_provider_style',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layer',
            name='cercle_icon',
            field=models.ImageField(upload_to=group.models.get_upload_path_layer_icon),
        ),
        migrations.AlterField(
            model_name='layer',
            name='square_icon',
            field=models.ImageField(upload_to=group.models.get_upload_path_layer_icon),
        ),
        migrations.AlterField(
            model_name='layer_provider_style',
            name='layer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='group.layer'),
        ),
    ]
