# Generated by Django 3.1.5 on 2021-01-30 22:13

from django.db import migrations, models
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_auto_20210130_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer_provider_style',
            name='ordre',
            field=models.IntegerField(default=1),
        ),
    ]
