# Generated by Django 3.1.7 on 2021-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0024_auto_20210213_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='icon_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        )
    ]
