# Generated by Django 3.1.7 on 2021-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0025_auto_20210306_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='icon_background',
            field=models.BooleanField(default=True),
        ),
    ]
