# Generated by Django 3.1.7 on 2021-03-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0026_auto_20210306_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='icon',
            name='tags',
        ),
        migrations.AddField(
            model_name='icon',
            name='tags',
            field=models.ManyToManyField(blank=True, to='group.TagsIcon'),
        ),
    ]
