# Generated by Django 3.1.7 on 2021-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0027_auto_20210307_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='group.TagsIcon'),
        ),
    ]
