# Generated by Django 3.1.7 on 2021-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0028_auto_20210307_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='tags',
            field=models.ManyToManyField(blank=True, to='group.TagsIcon'),
        )
    ]
