# Generated by Django 3.1.7 on 2021-03-12 21:51

from django.db import migrations, models
import django.db.models.deletion
import group.subModels.icon


class Migration(migrations.Migration):

    dependencies = [
        ('genericIcon', '0001_initial'),
        ('group', '0029_auto_20210307_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='path',
            field=models.FileField(default=None, upload_to=group.subModels.icon.get_upload_path),
        ),
       
        migrations.CreateModel(
            name='Base_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('protocol_carto', models.CharField(choices=[('wmts', 'Wmts'), ('wms', 'Wms')], max_length=5)),
                ('identifiant', models.TextField(blank=True, null=True)),
                ('attribution', models.TextField(blank=True, null=True)),
                ('picto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genericIcon.picto')),
            ],
        ),
    ]
