# Generated by Django 3.2.8 on 2021-11-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0031_auto_20211101_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_map',
            name='principal',
            field=models.BooleanField(default=False),
        )
    ]
