# Generated by Django 3.2.8 on 2021-11-06 13:01

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0032_auto_20211101_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_map',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base_map',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now().strftime("%Y-%m-%d %H:%M:%S") ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='layer_provider_style',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now().strftime("%Y-%m-%d %H:%M:%S") ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer_provider_style',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='map',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now().strftime("%Y-%m-%d %H:%M:%S") ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now().strftime("%Y-%m-%d %H:%M:%S") ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now().strftime("%Y-%m-%d %H:%M:%S") ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='layer_provider_style',
            unique_together=set(),
        ),
    ]
