# Generated by Django 3.2.12 on 2022-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0035_alter_group_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer_provider_style',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
