# Generated by Django 3.2.25 on 2024-09-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0036_alter_layer_provider_style_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
