import environ

env = environ.Env()
environ.Env.read_env()

OSM_CLIENT_ID = env("OSM_CLIENT_ID")
OSM_CLIENT_SECRET_ID = env("OSM_CLIENT_SECRET_ID")
OSM_REDIRECT_URL = env("OSM_REDIRECT_URL")

OSM_AUTHORIZATION_URL = env("OSM_AUTHORIZATION_URL")
TOKEN_URL = env("TOKEN_URL")
OSM_USER_DETAIL_URL = env("OSM_USER_DETAIL_URL")
OSM_API_URL = env("OSM_API_URL")
