# Generated by Django 3.1.1 on 2020-09-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osm_querry',
            name='id',
        ),
        migrations.AlterField(
            model_name='osm_querry',
            name='osm_querry_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
