# Generated by Django 3.2.12 on 2022-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0002_auto_20220408_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplequerry',
            name='sql',
            field=models.TextField(),
        ),
    ]
