# Generated by Django 3.1.1 on 2020-09-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0002_auto_20200920_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='osm_querry',
            new_name='querry',
        ),
    ]
