# Generated by Django 3.2.13 on 2022-05-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0003_alter_simplequerry_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplequerry',
            name='auto_update',
            field=models.BooleanField(default=True),
        ),
    ]
