# Generated by Django 3.1.1 on 2020-09-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0003_auto_20200920_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.IntegerField()),
                ('layer_id', models.IntegerField()),
                ('geometry_type', models.CharField(choices=[('Polygon', 'Polygon'), ('Point', 'Point'), ('LineString', 'Linestring')], max_length=11)),
            ],
        ),
    ]
