# Generated by Django 3.1.1 on 2020-09-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('osm', '0004_id_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_layer',
            name='layer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.layer'),
        ),
    ]
