# Generated by Django 3.1.2 on 2020-10-23 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20201017_2155'),
        ('osm', '0005_auto_20200920_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querry',
            old_name='select_clause',
            new_name='where',
        ),
        migrations.RemoveField(
            model_name='querry',
            name='geometry_type',
        ),
        migrations.RemoveField(
            model_name='querry',
            name='where_clause',
        ),
        migrations.AddField(
            model_name='querry',
            name='osm_vector_provider_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='provider.vector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querry',
            name='select',
            field=models.TextField(default='A.osm_id,A.name,A.amenity,hstore_to_json(A.tags), ST_TRANSFORM(A.way,4326) as geom'),
        ),
        migrations.AlterField(
            model_name='querry',
            name='osm_querry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
