# Generated by Django 3.1.2 on 2020-10-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20201017_2155'),
        ('osm', '0006_auto_20201023_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querry',
            name='osm_querry_id',
        ),
        migrations.AlterField(
            model_name='querry',
            name='osm_vector_provider_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='provider.vector'),
        ),
    ]
