# Generated by Django 3.1.2 on 2020-10-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0007_auto_20201023_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querry',
            old_name='osm_vector_provider_id',
            new_name='provider_vector_id',
        ),
    ]
