# Generated by Django 3.1.2 on 2020-10-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0010_auto_20201023_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='querry',
            name='sql',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='querry',
            name='select',
            field=models.TextField(blank=True),
        ),
    ]
