# Generated by Django 3.1.3 on 2020-11-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0011_auto_20201024_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querry',
            name='select',
            field=models.TextField(blank=True, null=True),
        ),
    ]
