# Generated by Django 3.1.2 on 2020-10-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='state',
            field=models.CharField(choices=[('good', 'Good'), ('not_working', 'Not Working'), ('action_require', 'Action Require'), ('unknow', 'Unknow')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='vector',
            name='provider_vector_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vector',
            name='shema',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vector',
            name='table',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vector',
            name='z_max',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='vector',
            name='z_min',
            field=models.IntegerField(default=0),
        ),
    ]
