# Generated by Django 3.1.2 on 2020-10-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20201017_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='epsg',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='id_server',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='shema',
            field=models.TextField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='table',
            field=models.TextField(default=None, max_length=15, null=True),
        ),
    ]
