# Generated by Django 3.1.3 on 2020-11-12 15:12

from django.db import migrations, models
import django.db.models.deletion
import provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20201017_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_style',
            fields=[
                ('custom_style_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('icon', models.FileField(blank=True, default=None, upload_to=provider.models.get_custom_style_icon_path)),
                ('class_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='style',
            name='custom_style_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.custom_style'),
        ),
    ]
