# Generated by Django 3.1.3 on 2020-11-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20201112_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='ol',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='pictogram',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
