# Generated by Django 3.1.3 on 2020-11-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20201112_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='vector_id',
            new_name='provider_vector_id',
        ),
        migrations.AlterField(
            model_name='style',
            name='provider_style_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
