# Generated by Django 3.1.3 on 2020-11-13 10:22

from django.db import migrations, models
import provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20201112_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='qml_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=provider.models.get_custom_qml_path),
        ),
    ]
