# Generated by Django 3.1.3 on 2020-11-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_style_qml_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='path_qgis',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='style',
            unique_together={('name', 'provider_vector_id')},
        ),
        migrations.AlterUniqueTogether(
            name='vector',
            unique_together={('id_server', 'path_qgis')},
        ),
    ]
