# Generated by Django 3.1.3 on 2020-11-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_auto_20201121_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='path_qgis',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
