# Generated by Django 3.1.3 on 2020-11-22 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_auto_20201121_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='extent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=None, null=True, size=4),
        ),
        migrations.AlterField(
            model_name='vector',
            name='path_qgis',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
