# Generated by Django 3.1.7 on 2021-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_auto_20201122_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
