# Generated by Django 3.2.6 on 2021-08-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_auto_20210826_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_style',
            name='custom_style_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
