# Generated by Django 3.2.6 on 2021-09-05 13:04

from django.db import migrations, models
import provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_alter_custom_style_custom_style_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_style',
            name='geometry_type',
            field=models.CharField(choices=[('Polygon', 'Polygon'), ('Point', 'Point'), ('LineString', 'Linestring')], max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custom_style',
            name='icon',
            field=models.ImageField(blank=True, default=None, upload_to=provider.models.get_custom_style_icon_path),
        ),
        migrations.AlterField(
            model_name='style',
            name='pictogram',
            field=models.ImageField(blank=True, upload_to='cars'),
        ),
    ]
