# Generated by Django 3.2.8 on 2021-11-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_auto_20210905_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_style',
            name='icon',
            field=models.ImageField(blank=True, default=None, upload_to='customStyle/'),
        ),
        migrations.AlterField(
            model_name='style',
            name='pictogram',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
