# Generated by Django 3.2.8 on 2021-11-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0016_auto_20211106_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
