# Generated by Django 3.2.10 on 2022-01-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0017_style_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='download_number',
            field=models.IntegerField(default=0),
        ),
    ]
