# Generated by Django 3.2.12 on 2022-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0018_vector_download_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='source',
            field=models.TextField(blank=True, choices=[('osm', 'Osm'), ('querry', 'Querry')], max_length=15, null=True),
        ),
    ]
