# Generated by Django 3.2.13 on 2022-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0019_vector_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='primary_key_field',
            field=models.CharField(default='osm_id', max_length=50),
        ),
    ]
