# Generated by Django 3.2.13 on 2022-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0021_alter_vector_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_style',
            name='geometry_type',
            field=models.CharField(choices=[('Polygon', 'Polygon'), ('Point', 'Point'), ('LineString', 'Linestring'), ('None', 'Null')], max_length=11),
        ),
        migrations.AlterField(
            model_name='vector',
            name='geometry_type',
            field=models.CharField(choices=[('Polygon', 'Polygon'), ('Point', 'Point'), ('LineString', 'Linestring'), ('None', 'Null')], max_length=11),
        ),
    ]
