# Generated by Django 3.2.13 on 2022-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0022_auto_20220625_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_style',
            name='geometry_type',
            field=models.CharField(choices=[('Polygon', 'Polygon'), ('Point', 'Point'), ('LineString', 'Linestring'), ('null', 'Null')], max_length=11),
        ),
        migrations.AlterField(
            model_name='vector',
            name='geometry_type',
            field=models.CharField(choices=[('Polygon', 'Polygon'), ('Point', 'Point'), ('LineString', 'Linestring'), ('null', 'Null')], max_length=11),
        ),
    ]
