# Generated by Django 3.2.25 on 2024-05-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0023_auto_20220625_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_style',
            old_name='fucntion_name',
            new_name='function_name',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='source',
            new_name='type',
        ),
    ]
