# Generated by Django 3.1.7 on 2021-03-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0011_auto_20210306_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('extent_pk', models.BigIntegerField(blank=True, null=True)),
                ('extent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.vector')),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.map')),
            ],
        ),
        migrations.CreateModel(
            name='AdminBoundary',
            fields=[
                ('admin_boundary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.vector')),
            ],
        ),
    ]
