# Generated by Django 3.2.8 on 2021-11-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
