# Generated by Django 3.2.25 on 2025-02-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npsfeedback',
            name='has_send_no_response',
            field=models.BooleanField(default=False),
        ),
    ]
