# Generated by Django 3.2.25 on 2025-02-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_npsfeedback_has_send_no_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npsfeedback',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
